### PR TITLE
feat: add support for qs options

### PR DESCRIPTION
**Pull request by daniel-parakey**
Closes https://github.com/moleculerjs/moleculer-web/issues/309

### CODE REVIEW

**Review by intech — APPROVED** [review]
LGTM

**Review by intech — APPROVED** [review]

**Comment by daniel-parakey** [comment]
Made a mistake where I put the parameter inside the `routes` object in `index.d.ts`. Force-pushed a new version

**Review by intech — APPROVED** [review]

**Comment by daniel-parakey** [comment]
@icebob do you have an ETA of when this might be approved/merged? We're using my fork for the time being, but having this in master would be nice.

**Review by icebob — APPROVED** [review]
Nice job! Could you help to mention this new options [in the docs](https://github.com/moleculerjs/site/blob/master/source/docs/0.14/moleculer-web.md) as well?

**Comment by icebob** [comment]
> @icebob do you have an ETA of when this might be approved/merged? We're using my fork for the time being, but having this in master would be nice.

I plan to release it at the weekend.

**Comment by daniel-parakey** [comment]
@icebob nice, thanks! Docs change can be found here: https://github.com/moleculerjs/site/pull/202

**Pull request merged**
