### PR TITLE
added multiple REST routes in service settings

### PR DESCRIPTION
**Pull request by mariusbackes**
In my application I need the possibility to define several REST routes for a service. With this change it is possible to define an array of routes.

```
settings: {
  rest: ["/route", "/route/multi"]
},

actions: {
  test: {
    rest: "GET /test"
    ...
  }
}
```

Both routes ```/route/test``` and ```/route/multi/test``` call the specific action.

### CODE REVIEW

**Comment by mariusbackes** [comment]
The test run for Node 8 is not sucessfully because jest has dropped the node 8 support with the major release of 26.0.0. [#9423](https://github.com/facebook/jest/pull/9423)

**Comment by icebob** [comment]
Cool, thanks! By the way, would be useful supporting multi REST config in action schema as well. 
```js
actions: {
  test: {
    rest: ["GET /test", "POST /test2"]
    ...
  }
}
```

Maybe do you have time to work on as well in this PR?

**Comment by mariusbackes** [comment]
I have added an array for each rest route. I have also updated the test cases

**Comment by icebob** [comment]
Awesome, thank, I will check it today.

**Review by icebob — APPROVED** [review]
Nice job! Thanks!

**Pull request merged**
