### PR TITLE
fix: #298: register on close and error event on response

### LINKED ISSUE #298: Possible memory leak on alias with custom function on error
## Description

I have noticed a strange behaviour when declaring some alias with a custom function that triggers an error on the response. It seems that when the response is not closed correctly, for example on an error, the context remains pending and it is not closed correctly. To simulate this behaviour it should be enough to call `res.destroy()`.

## Expected behaviour 

I was expecting the context gets correctly disposed when the res somehow is closed or destroyed. On hundreds of calls the memory gets filled up and the memory leak is more evident. It seems that in this case the event `finish` is not enough to listen to in order to dispose the context:

https://github.com/moleculerjs/moleculer-web/blob/65b7addddc3dc34856d2a3bf6fe202664b2e033c/src/index.js#L418

## Reproduction example

https://codesandbox.io/s/res-destroy-memory-leak-igq1i?file=/public/index.html

## Workaround

Handling the `res.on('close')` error and emitting `res.emit('finish')` once, should fix this behaviour.

### PR DESCRIPTION
**Pull request by giovanni-bertoncelli**
Resolves #298.
Added handlers to handle `error` and `close` events on response and resolve/reject respectively the context caller.

### CODE REVIEW

**Comment by icebob** [comment]
Great, thanks!

**Comment by giovanni-bertoncelli** [comment]
@icebob maybe the call should be always resolved instead of rejected since if rejected moleculer tries to write the headers, but since the response stream has already started the headers are surely already been written.

**Comment by icebob** [comment]
Can we check that the response stream is started? And in this case, we block the header sending.

**Comment by giovanni-bertoncelli** [comment]
@icebob how can we do that? By resolving if `headersSent` is `true`? And rejecting otherwise?

(BTW @michelevincenzi is my colleague, we're working together on this)

**Comment by icebob** [comment]
we can reject, but check the `headersSent` value in `sendError`.

**Pull request merged**
