### PR TITLE
Fix cors problem in assets

### PR DESCRIPTION
**Pull request by moonrailgun**
If we use assets, and send OPTIONS(preflight) request for this assets
Its will return 404 because of its not match any action.

### CODE REVIEW

**Comment by moonrailgun** [comment]
Hi @icebob , i try to fix ci problem and pass all test in my local  env. Can you restart workflows again? thanks

**Comment by moonrailgun** [comment]
> Hi @icebob , i try to fix ci problem and pass all test in my local env. Can you restart workflows again? thanks

Sorry, i just pass `integration` tests before. my mistake. 

Now i have pass all test case without platform encoding problem in window. Pls restart ci workflow again, thanks. (This problem not like appear in *uix system)
image

**Review by icebob — CHANGES_REQUESTED** [review]
Would be good some test to cover the new function.

**Review by icebob — APPROVED** [review]
Good job, thanks!

**Pull request merged**
