### PR TITLE
Auto generate ETag & freshness check

### LINKED ISSUE #91: [Feature Request] Cache Control
- Auto generate etag http://expressjs.com/zh-cn/api.html#etag.options.table
- Return 304 according to the request and response headers. (can use [this lib](https://www.npmjs.com/package/fresh))

### PR DESCRIPTION
**Pull request by tiaod**
Fix #91

### CODE REVIEW

**Comment by tiaod** [comment]
# Freshness check
```js
module.exports = {
  name: "rss",
  actions: {
    feed(ctx) {
      ctx.meta.$responseHeaders = {
        "Last-Modified": "Tue, 24 Feb 2018 08:01:04 GMT"
      }
      return rssFeed
    },
    async getItem(ctx){
      let item = await getRssItem(ctx.params.id)
      ctx.meta.$responseHeaders = {
        "ETag": item.hash
      }
      return item
    }
  }
}
```

# Auto generate etag
Service settings:
```js
settings: {
  etag: true
}
```
Will only generate ETag for none stream response. If you want to stream your response, you should generate the etag by yourself.
```js
module.exports = {
  name: "export",
  actions: {
    // Download response as a file in the browser
    downloadCSV(ctx) {
      ctx.meta.$responseType = "text/csv";
      ctx.meta.$responseHeaders = {
        "Content-Disposition": `attachment; filename="data-${ctx.params.id}.csv"`,
        "ETag": '<your etag here>'
      };
      return csvFileStream;
    }
}
```

**Comment by icebob** [comment]
Great, thank you! Please cover this ETag functionality with tests.

**Comment by tiaod** [comment]
Done

**Comment by icebob** [comment]
Thanks @tiaod,
I've made some changes:
- moved the `etag` setting to route level instead of service level. 
- change the default to false because hash calculation is a time-consuming operation and breaks the performance.
- removed `weak: true` ETag option, because weak works only with `fs.Stats` entity but API Gateway never use it, so it always will use strong ETags

**Comment by icebob** [comment]
Ok, we can change it to express-like, but if you check the source of `etag`, you will see, weak mode works only if you pass an FsStat instance for the generator function:
https://github.com/jshttp/etag/blob/4664b6e53c85a56521076f9c5004dd9626ae10c8/index.js#L76-L79
So with API Gateway it never use weak etags. Use strong hashes just put `W/` before the hash :)
But the custom generation function is good idea.

**Comment by icebob** [comment]
I've updated. So now it has the following value:
- `etag: true,` - weak hashing
- `etag: false,` - no ETag
- `etag: "weak",` - weak hashing
- `etag: "strong",` - strong hashing
- `etag: body => hash(body),` - custom hash function.

And you can set it in service settings and route setting as well. Route setting overwrite service setting.

**Comment by tiaod** [comment]
I'm living in GMT+8 and good morning! 😄 

I think the weak mode of `etag` is not only for `fs.state`, It certainly has other uses. The `etag` docs says that:
> **etag(entity, [options])**
Generate a strong ETag for the given entity. This should be the complete body of the entity. Strings, Buffers, and fs.Stats are accepted. By default, a strong ETag is generated except for fs.Stats, which will generate a weak ETag (this can be overwritten by options.weak).

After some search, I found the difference between the strong and weak ETag:
- Strong ETag indicates that resource content is same for response body and the response headers.
- Weak ETag indicates that the two representations are semantically equivalent. It compares only the response body.

But I am still very confused which should I use. 😅 Finally, I decided to follow the express, to use the weak etag by default. Do what express do is right!

**Comment by HighSoftWare96** [comment]
Excuse me guys but why no `Cache-Control` header is attached when using the Etag?

**Comment by icebob** [comment]
Cache-Control & ETag are [two different caching solutions](https://medium.com/pixelpoint/best-practices-for-cache-control-settings-for-your-website-ff262b38c5a2). Using ETag, no need Cache-Control headers.

**Pull request merged**
